[build]
  command = "npm run build && node netlify-build.js"
  publish = "out"

# Handle the about page directly without redirects
[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about.html"
  to = "/about/index.html"
  status = 200
  force = true

# Service worker should be served with correct content type
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

# Handle all routes with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirect for movie detail pages
[[redirects]]
  from = "/movies/*"
  to = "/movies/_fallback.html"
  status = 200

# Add cache control headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Enable Netlify Edge Functions
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Configure build hooks
[build.processing]
  skip_processing = false 