[build]
  command = "npm run netlify-build:optimized"
  publish = "out"

# Handle all routes with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirect for movie detail pages
[[redirects]]
  from = "/movies/*"
  to = "/movies/_fallback.html"
  status = 200

# Add cache control headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'"
    Cross-Origin-Opener-Policy = "same-origin"

# Add Brotli and Gzip compression support
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "text/html"
    Cache-Control = "public, max-age=0, must-revalidate"

# Fallback to Gzip for browsers that don't support Brotli
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"
  [headers.conditions]
    Accept-Encoding = "gzip"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"
  [headers.conditions]
    Accept-Encoding = "gzip"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "text/html"
    Cache-Control = "public, max-age=0, must-revalidate"
  [headers.conditions]
    Accept-Encoding = "gzip"

# Cache static assets for a year
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable Netlify Edge Functions
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Configure build hooks
[build.processing]
  skip_processing = false 